### ISSUE TITLE
Undefined index: default？

### ISSUE THREAD

**Issue by piian** [summerblue/generator#8]
代码一模一样，命令行弹出错误
``` 
[ErrorException]
  Undefined index: default
```

**Comment by summerblue** [comment]
把 storage/logs/laravel.log  里的相关信息给我下

**Comment by piian** [comment]
```
[2017-11-06 16:05:55] local.ERROR: Undefined index: default {"exception":"[object] (ErrorException(code: 0): Undefined index: default at D:\\www\\git\\laravel-admin\\vendor\\summerblue\\generator\\src\\Makes\\MakeView.php:133)
[stacktrace]
#0 D:\\www\\git\\laravel-admin\\vendor\\summerblue\\generator\\src\\Makes\\MakeView.php(133): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'D:\\\\www\\\\git\\\\lara...', 133, Array)
#1 D:\\www\\git\\laravel-admin\\vendor\\summerblue\\generator\\src\\Makes\\MakeView.php(86): Summerblue\\Generator\\Makes\\MakeView->getFields('bs3', 'fillable')
#2 D:\\www\\git\\laravel-admin\\vendor\\summerblue\\generator\\src\\Makes\\MakeView.php(47): Summerblue\\Generator\\Makes\\MakeView->start()
#3 D:\\www\\git\\laravel-admin\\vendor\\summerblue\\generator\\src\\Commands\\ScaffoldMakeCommand.php(194): Summerblue\\Generator\\Makes\\MakeView->__construct(Object(Summerblue\\Generator\\Commands\\ScaffoldMakeCommand), Object(Illuminate\\Filesystem\\Filesystem))
#4 D:\\www\\git\\laravel-admin\\vendor\\summerblue\\generator\\src\\Commands\\ScaffoldMakeCommand.php(98): Summerblue\\Generator\\Commands\\ScaffoldMakeCommand->makeViews()
#5 [internal function]: Summerblue\\Generator\\Commands\\ScaffoldMakeCommand->handle()
#6 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#7 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(180): Illuminate\\Container\\Container->call(Array)
#11 D:\\www\\git\\laravel-admin\\vendor\\symfony\\console\\Command\\Command.php(262): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 D:\\www\\git\\laravel-admin\\vendor\\symfony\\console\\Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 D:\\www\\git\\laravel-admin\\vendor\\symfony\\console\\Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(Summerblue\\Generator\\Commands\\ScaffoldMakeCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 D:\\www\\git\\laravel-admin\\vendor\\symfony\\console\\Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 D:\\www\\git\\laravel-admin\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 D:\\www\\git\\laravel-admin\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
"} 
```

**Comment by summerblue** [comment]
![image](https://user-images.githubusercontent.com/324764/32432587-0e67e788-c313-11e7-89d8-d38ae6fa9a41.png)

https://fsdhub.com/books/laravel-intermediate-training-5.5/647/code-generator#comments-1766
